version: "3.7"
services:
  database:
    image: mongo:6.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=cards
      - MONGO_INITDB_USERNAME=mongo
      - MONGO_INITDB_PASSWORD=mongo
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db

  api:
    build:
      context: ./rbh-be
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - PORT=3000
      - MONGO_DB_URI=mongodb://mongo:mongo@rbh-database-1:27017/cards
    volumes:
      - ./rbh-be:/usr/src/app

  client:
    build: ./rbh-fe
    ports:
      - 5173:5173
    depends_on:
      - api